# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-21 22:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0010_auto_20161021_1735'),
        ('events', '0013_auto_20160622_1246'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_id', models.CharField(max_length=255, unique=True)),
                ('source', models.CharField(max_length=100)),
                ('currency', models.CharField(default='usd', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('amount_refunded', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('description', models.TextField(blank=True)),
                ('paid', models.NullBooleanField()),
                ('refunded', models.NullBooleanField()),
                ('captured', models.NullBooleanField()),
                ('receipt_sent', models.BooleanField(default=False)),
                ('charge_created', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='unknown', max_length=20)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='events.Event')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='core.Member')),
            ],
        ),
    ]
