# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import migrations, models
from django.conf import settings
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20151106_1953'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('rounds', models.IntegerField(default=1)),
                ('holes', models.IntegerField(default=18)),
                ('signup_start', models.DateTimeField()),
                ('signup_end', models.DateTimeField()),
                ('start_time', models.TimeField()),
                ('event_fee', models.DecimalField(max_digits=5, decimal_places=2)),
                ('skins_fee', models.DecimalField(max_digits=5, decimal_places=2)),
                ('minimum_signup_group_size', models.IntegerField(default=1)),
                ('maximum_signup_group_size', models.IntegerField(default=1)),
                ('group_size', models.IntegerField(default=4)),
                ('is_shotgun_start', models.BooleanField(default=False)),
                ('can_signup_group', models.BooleanField(default=False)),
                ('can_choose_hole', models.BooleanField(default=False)),
                ('scoring', models.CharField(choices=[('IN', 'Individual'), ('T1', 'Team: One Score'), ('TM', 'Team: Multiple Scores')], default='IN', max_length=2)),
                ('scoring_system', models.CharField(choices=[('SP', 'Stroke Play'), ('SF', 'Stableford'), ('CH', 'Chicago')], default='SP', max_length=2)),
                ('team_scoring', models.CharField(choices=[('NA', 'Not a Team Event'), ('BB', 'Best Ball'), ('AGG', 'Aggregate')], default='NA', max_length=2)),
                ('number_of_scores', models.IntegerField(default=1)),
                ('courses', models.ManyToManyField(to='courses.CourseSetup')),
            ],
        ),
        migrations.CreateModel(
            name='EventTemplate',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(unique=True, max_length=100)),
                ('description', models.TextField()),
                ('rounds', models.IntegerField(default=1)),
                ('holes', models.IntegerField(default=18)),
                ('event_fee', models.DecimalField(max_digits=5, decimal_places=2)),
                ('skins_fee', models.DecimalField(max_digits=5, decimal_places=2)),
                ('minimum_signup_group_size', models.IntegerField(default=1)),
                ('maximum_signup_group_size', models.IntegerField(default=1)),
                ('group_size', models.IntegerField(default=4)),
                ('is_shotgun_start', models.BooleanField(default=False)),
                ('can_signup_group', models.BooleanField(default=False)),
                ('can_choose_hole', models.BooleanField(default=False)),
                ('scoring', models.CharField(choices=[('IN', 'Individual'), ('T1', 'Team: One Score'), ('TM', 'Team: Multiple Scores')], default='IN', max_length=2)),
                ('scoring_system', models.CharField(choices=[('SP', 'Stroke Play'), ('SF', 'Stableford'), ('CH', 'Chicago')], default='SP', max_length=2)),
                ('team_scoring', models.CharField(choices=[('NA', 'Not a Team Event'), ('BB', 'Best Ball'), ('AGG', 'Aggregate')], default='NA', max_length=2)),
                ('number_of_scores', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalEvent',
            fields=[
                ('id', models.IntegerField(verbose_name='ID', db_index=True, auto_created=True, blank=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('rounds', models.IntegerField(default=1)),
                ('holes', models.IntegerField(default=18)),
                ('signup_start', models.DateTimeField()),
                ('signup_end', models.DateTimeField()),
                ('start_time', models.TimeField()),
                ('event_fee', models.DecimalField(max_digits=5, decimal_places=2)),
                ('skins_fee', models.DecimalField(max_digits=5, decimal_places=2)),
                ('minimum_signup_group_size', models.IntegerField(default=1)),
                ('maximum_signup_group_size', models.IntegerField(default=1)),
                ('group_size', models.IntegerField(default=4)),
                ('is_shotgun_start', models.BooleanField(default=False)),
                ('can_signup_group', models.BooleanField(default=False)),
                ('can_choose_hole', models.BooleanField(default=False)),
                ('scoring', models.CharField(choices=[('IN', 'Individual'), ('T1', 'Team: One Score'), ('TM', 'Team: Multiple Scores')], default='IN', max_length=2)),
                ('scoring_system', models.CharField(choices=[('SP', 'Stroke Play'), ('SF', 'Stableford'), ('CH', 'Chicago')], default='SP', max_length=2)),
                ('team_scoring', models.CharField(choices=[('NA', 'Not a Team Event'), ('BB', 'Best Ball'), ('AGG', 'Aggregate')], default='NA', max_length=2)),
                ('number_of_scores', models.IntegerField(default=1)),
                ('history_id', models.AutoField(serialize=False, primary_key=True)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, related_name='+')),
            ],
            options={
                'verbose_name': 'historical event',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
        ),
        migrations.CreateModel(
            name='HistoricalEventTemplate',
            fields=[
                ('id', models.IntegerField(verbose_name='ID', db_index=True, auto_created=True, blank=True)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('description', models.TextField()),
                ('rounds', models.IntegerField(default=1)),
                ('holes', models.IntegerField(default=18)),
                ('event_fee', models.DecimalField(max_digits=5, decimal_places=2)),
                ('skins_fee', models.DecimalField(max_digits=5, decimal_places=2)),
                ('minimum_signup_group_size', models.IntegerField(default=1)),
                ('maximum_signup_group_size', models.IntegerField(default=1)),
                ('group_size', models.IntegerField(default=4)),
                ('is_shotgun_start', models.BooleanField(default=False)),
                ('can_signup_group', models.BooleanField(default=False)),
                ('can_choose_hole', models.BooleanField(default=False)),
                ('scoring', models.CharField(choices=[('IN', 'Individual'), ('T1', 'Team: One Score'), ('TM', 'Team: Multiple Scores')], default='IN', max_length=2)),
                ('scoring_system', models.CharField(choices=[('SP', 'Stroke Play'), ('SF', 'Stableford'), ('CH', 'Chicago')], default='SP', max_length=2)),
                ('team_scoring', models.CharField(choices=[('NA', 'Not a Team Event'), ('BB', 'Best Ball'), ('AGG', 'Aggregate')], default='NA', max_length=2)),
                ('number_of_scores', models.IntegerField(default=1)),
                ('history_id', models.AutoField(serialize=False, primary_key=True)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, related_name='+')),
            ],
            options={
                'verbose_name': 'historical event template',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
        ),
    ]
