# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-07 19:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20160207_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='template',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='events.EventTemplate'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventtemplate',
            name='notes',
            field=models.TextField(default=1, verbose_name='Additional notes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='template',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='events.EventTemplate'),
        ),
        migrations.AddField(
            model_name='historicaleventtemplate',
            name='notes',
            field=models.TextField(default=1, verbose_name='Additional notes'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='notes',
            field=models.TextField(verbose_name='Additional notes'),
        ),
        migrations.AlterField(
            model_name='historicalevent',
            name='notes',
            field=models.TextField(verbose_name='Additional notes'),
        ),
    ]
