# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-07 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20160207_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='team_scoring',
        ),
        migrations.RemoveField(
            model_name='eventtemplate',
            name='team_scoring',
        ),
        migrations.RemoveField(
            model_name='historicalevent',
            name='team_scoring',
        ),
        migrations.RemoveField(
            model_name='historicaleventtemplate',
            name='team_scoring',
        ),
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(default='M', max_length=1, verbose_name='Event type'),
        ),
        migrations.AddField(
            model_name='event',
            name='season_points',
            field=models.IntegerField(default=0, verbose_name='Season long points available'),
        ),
        migrations.AddField(
            model_name='eventtemplate',
            name='event_type',
            field=models.CharField(default='M', max_length=1, verbose_name='Event type'),
        ),
        migrations.AddField(
            model_name='eventtemplate',
            name='season_points',
            field=models.IntegerField(default=0, verbose_name='Season long points available'),
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='event_type',
            field=models.CharField(default='M', max_length=1, verbose_name='Event type'),
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='season_points',
            field=models.IntegerField(default=0, verbose_name='Season long points available'),
        ),
        migrations.AddField(
            model_name='historicaleventtemplate',
            name='event_type',
            field=models.CharField(default='M', max_length=1, verbose_name='Event type'),
        ),
        migrations.AddField(
            model_name='historicaleventtemplate',
            name='season_points',
            field=models.IntegerField(default=0, verbose_name='Season long points available'),
        ),
        migrations.AlterField(
            model_name='event',
            name='number_of_scores',
            field=models.CharField(blank=True, default='1', max_length=12, verbose_name='Number of scores'),
        ),
        migrations.AlterField(
            model_name='event',
            name='scoring',
            field=models.CharField(choices=[('IN', 'Individual'), ('TBB', 'Team: Best Ball'), ('TAG', 'Team: Aggregate Score'), ('TS', 'Team: Scramble')], default='IN', max_length=3, verbose_name='Scoring type'),
        ),
        migrations.AlterField(
            model_name='eventtemplate',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Event title'),
        ),
        migrations.AlterField(
            model_name='eventtemplate',
            name='number_of_scores',
            field=models.CharField(blank=True, default='1', max_length=12, verbose_name='Number of scores'),
        ),
        migrations.AlterField(
            model_name='eventtemplate',
            name='scoring',
            field=models.CharField(choices=[('IN', 'Individual'), ('TBB', 'Team: Best Ball'), ('TAG', 'Team: Aggregate Score'), ('TS', 'Team: Scramble')], default='IN', max_length=3, verbose_name='Scoring type'),
        ),
        migrations.AlterField(
            model_name='eventtemplate',
            name='skins_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Skins fee'),
        ),
        migrations.AlterField(
            model_name='historicalevent',
            name='number_of_scores',
            field=models.CharField(blank=True, default='1', max_length=12, verbose_name='Number of scores'),
        ),
        migrations.AlterField(
            model_name='historicalevent',
            name='scoring',
            field=models.CharField(choices=[('IN', 'Individual'), ('TBB', 'Team: Best Ball'), ('TAG', 'Team: Aggregate Score'), ('TS', 'Team: Scramble')], default='IN', max_length=3, verbose_name='Scoring type'),
        ),
        migrations.AlterField(
            model_name='historicaleventtemplate',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Event title'),
        ),
        migrations.AlterField(
            model_name='historicaleventtemplate',
            name='number_of_scores',
            field=models.CharField(blank=True, default='1', max_length=12, verbose_name='Number of scores'),
        ),
        migrations.AlterField(
            model_name='historicaleventtemplate',
            name='scoring',
            field=models.CharField(choices=[('IN', 'Individual'), ('TBB', 'Team: Best Ball'), ('TAG', 'Team: Aggregate Score'), ('TS', 'Team: Scramble')], default='IN', max_length=3, verbose_name='Scoring type'),
        ),
        migrations.AlterField(
            model_name='historicaleventtemplate',
            name='skins_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Skins fee'),
        ),
    ]
