# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-22 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20160207_1215'),
        ('events', '0010_eventcoursesetup_historicaleventcoursesetup'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='course_setups',
            field=models.ManyToManyField(to='courses.CourseSetup', verbose_name='Course(s)'),
        ),
        migrations.AddField(
            model_name='event',
            name='registration_maximum',
            field=models.IntegerField(default=0, verbose_name='Registration max (non-league events)'),
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='registration_maximum',
            field=models.IntegerField(default=0, verbose_name='Registration max (non-league events)'),
        ),
    ]
