# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-22 17:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_auto_20160622_1222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventcoursesetup',
            name='course_setup',
        ),
        migrations.RemoveField(
            model_name='eventcoursesetup',
            name='event',
        ),
        migrations.RemoveField(
            model_name='historicaleventcoursesetup',
            name='course_setup',
        ),
        migrations.RemoveField(
            model_name='historicaleventcoursesetup',
            name='event',
        ),
        migrations.RemoveField(
            model_name='historicaleventcoursesetup',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='EventCourseSetup',
        ),
        migrations.DeleteModel(
            name='HistoricalEventCourseSetup',
        ),
    ]
