# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-22 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_auto_20160622_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='course_setups',
            field=models.ManyToManyField(blank=True, to='courses.CourseSetup', verbose_name='Course(s)'),
        ),
    ]
