# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-30 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_auto_20161023_0847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='event',
            name='number_of_scores',
        ),
        migrations.RemoveField(
            model_name='event',
            name='scoring',
        ),
        migrations.RemoveField(
            model_name='event',
            name='scoring_system',
        ),
        migrations.RemoveField(
            model_name='eventtemplate',
            name='number_of_scores',
        ),
        migrations.RemoveField(
            model_name='eventtemplate',
            name='scoring',
        ),
        migrations.RemoveField(
            model_name='eventtemplate',
            name='scoring_system',
        ),
        migrations.RemoveField(
            model_name='historicalevent',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='historicalevent',
            name='number_of_scores',
        ),
        migrations.RemoveField(
            model_name='historicalevent',
            name='scoring',
        ),
        migrations.RemoveField(
            model_name='historicalevent',
            name='scoring_system',
        ),
        migrations.RemoveField(
            model_name='historicaleventtemplate',
            name='number_of_scores',
        ),
        migrations.RemoveField(
            model_name='historicaleventtemplate',
            name='scoring',
        ),
        migrations.RemoveField(
            model_name='historicaleventtemplate',
            name='scoring_system',
        ),
        migrations.AlterField(
            model_name='event',
            name='event_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Event fee'),
        ),
        migrations.AlterField(
            model_name='event',
            name='skins_fee',
            field=models.DecimalField(blank=0.0, decimal_places=2, max_digits=5, verbose_name='Skins fee'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_type',
            field=models.CharField(choices=[('TT', 'Tee Times'), ('SG', 'Shotgun'), ('NA', 'Not Applicable')], default='NA', max_length=2, verbose_name='Start type'),
        ),
        migrations.AlterField(
            model_name='eventtemplate',
            name='event_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Event fee'),
        ),
        migrations.AlterField(
            model_name='eventtemplate',
            name='start_type',
            field=models.CharField(choices=[('TT', 'Tee Times'), ('SG', 'Shotgun'), ('NA', 'Not Applicable')], default='NA', max_length=2, verbose_name='Start type'),
        ),
        migrations.AlterField(
            model_name='historicalevent',
            name='event_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Event fee'),
        ),
        migrations.AlterField(
            model_name='historicalevent',
            name='skins_fee',
            field=models.DecimalField(blank=0.0, decimal_places=2, max_digits=5, verbose_name='Skins fee'),
        ),
        migrations.AlterField(
            model_name='historicalevent',
            name='start_type',
            field=models.CharField(choices=[('TT', 'Tee Times'), ('SG', 'Shotgun'), ('NA', 'Not Applicable')], default='NA', max_length=2, verbose_name='Start type'),
        ),
        migrations.AlterField(
            model_name='historicaleventtemplate',
            name='event_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Event fee'),
        ),
        migrations.AlterField(
            model_name='historicaleventtemplate',
            name='start_type',
            field=models.CharField(choices=[('TT', 'Tee Times'), ('SG', 'Shotgun'), ('NA', 'Not Applicable')], default='NA', max_length=2, verbose_name='Start type'),
        ),
    ]
