# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-30 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_auto_20161030_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='historicalevent',
            name='end_date',
        ),
        migrations.AlterField(
            model_name='event',
            name='signup_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Signup end'),
        ),
        migrations.AlterField(
            model_name='event',
            name='signup_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Signup start'),
        ),
        migrations.AlterField(
            model_name='historicalevent',
            name='signup_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Signup end'),
        ),
        migrations.AlterField(
            model_name='historicalevent',
            name='signup_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Signup start'),
        ),
    ]
