# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-10 23:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_auto_20161224_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='alt_event_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Alternative event fee'),
        ),
        migrations.AddField(
            model_name='event',
            name='cart_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Cart fee'),
        ),
        migrations.AddField(
            model_name='event',
            name='green_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Green fee'),
        ),
        migrations.AddField(
            model_name='eventtemplate',
            name='alt_event_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Alternative event fee'),
        ),
        migrations.AddField(
            model_name='eventtemplate',
            name='cart_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Cart fee'),
        ),
        migrations.AddField(
            model_name='eventtemplate',
            name='green_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Green fee'),
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='alt_event_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Alternative event fee'),
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='cart_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Cart fee'),
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='green_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Green fee'),
        ),
        migrations.AddField(
            model_name='historicaleventtemplate',
            name='alt_event_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Alternative event fee'),
        ),
        migrations.AddField(
            model_name='historicaleventtemplate',
            name='cart_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Cart fee'),
        ),
        migrations.AddField(
            model_name='historicaleventtemplate',
            name='green_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Green fee'),
        ),
        migrations.AlterField(
            model_name='eventtemplate',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Additional notes'),
        ),
        migrations.AlterField(
            model_name='historicaleventtemplate',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Additional notes'),
        ),
    ]
