# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-13 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_auto_20170110_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('L', 'League'), ('W', 'Weekend Major'), ('H', 'Holiday Pro-shop Event'), ('M', 'Member Meeting'), ('B', 'Board Meeting'), ('O', 'Other'), ('S', 'State Tournament'), ('R', 'Open Registration Period'), ('D', 'Deadline')], default='L', max_length=1, verbose_name='Event type'),
        ),
        migrations.AlterField(
            model_name='event',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Additional notes'),
        ),
        migrations.AlterField(
            model_name='eventtemplate',
            name='event_type',
            field=models.CharField(choices=[('L', 'League'), ('W', 'Weekend Major'), ('H', 'Holiday Pro-shop Event'), ('M', 'Member Meeting'), ('B', 'Board Meeting'), ('O', 'Other'), ('S', 'State Tournament'), ('R', 'Open Registration Period'), ('D', 'Deadline')], default='L', max_length=1, verbose_name='Event type'),
        ),
        migrations.AlterField(
            model_name='historicalevent',
            name='event_type',
            field=models.CharField(choices=[('L', 'League'), ('W', 'Weekend Major'), ('H', 'Holiday Pro-shop Event'), ('M', 'Member Meeting'), ('B', 'Board Meeting'), ('O', 'Other'), ('S', 'State Tournament'), ('R', 'Open Registration Period'), ('D', 'Deadline')], default='L', max_length=1, verbose_name='Event type'),
        ),
        migrations.AlterField(
            model_name='historicalevent',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Additional notes'),
        ),
        migrations.AlterField(
            model_name='historicaleventtemplate',
            name='event_type',
            field=models.CharField(choices=[('L', 'League'), ('W', 'Weekend Major'), ('H', 'Holiday Pro-shop Event'), ('M', 'Member Meeting'), ('B', 'Board Meeting'), ('O', 'Other'), ('S', 'State Tournament'), ('R', 'Open Registration Period'), ('D', 'Deadline')], default='L', max_length=1, verbose_name='Event type'),
        ),
    ]
