# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-12-26 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_auto_20170213_0652'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='portal_url',
            field=models.CharField(blank=True, max_length=240, null=True, verbose_name='Golf Genius Portal'),
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='portal_url',
            field=models.CharField(blank=True, max_length=240, null=True, verbose_name='Golf Genius Portal'),
        ),
    ]
