# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-01-01 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_auto_20171226_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='skins_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Online skins deadline'),
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='skins_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Online skins deadline'),
        ),
    ]
