# Generated by Django 2.1.4 on 2018-12-11 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_auto_20180101_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalevent',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicaleventtemplate',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('L', 'League'), ('W', 'Weekend Major'), ('H', 'Holiday Pro-shop Event'), ('M', 'Member Meeting'), ('B', 'Board Meeting'), ('O', 'Other'), ('S', 'State Tournament'), ('R', 'Open Registration Period'), ('D', 'Deadline'), ('X', 'Canceled')], default='L', max_length=1, verbose_name='Event type'),
        ),
        migrations.AlterField(
            model_name='event',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='events.EventTemplate'),
        ),
        migrations.AlterField(
            model_name='eventtemplate',
            name='event_type',
            field=models.CharField(choices=[('L', 'League'), ('W', 'Weekend Major'), ('H', 'Holiday Pro-shop Event'), ('M', 'Member Meeting'), ('B', 'Board Meeting'), ('O', 'Other'), ('S', 'State Tournament'), ('R', 'Open Registration Period'), ('D', 'Deadline'), ('X', 'Canceled')], default='L', max_length=1, verbose_name='Event type'),
        ),
        migrations.AlterField(
            model_name='historicalevent',
            name='event_type',
            field=models.CharField(choices=[('L', 'League'), ('W', 'Weekend Major'), ('H', 'Holiday Pro-shop Event'), ('M', 'Member Meeting'), ('B', 'Board Meeting'), ('O', 'Other'), ('S', 'State Tournament'), ('R', 'Open Registration Period'), ('D', 'Deadline'), ('X', 'Canceled')], default='L', max_length=1, verbose_name='Event type'),
        ),
        migrations.AlterField(
            model_name='historicaleventtemplate',
            name='event_type',
            field=models.CharField(choices=[('L', 'League'), ('W', 'Weekend Major'), ('H', 'Holiday Pro-shop Event'), ('M', 'Member Meeting'), ('B', 'Board Meeting'), ('O', 'Other'), ('S', 'State Tournament'), ('R', 'Open Registration Period'), ('D', 'Deadline'), ('X', 'Canceled')], default='L', max_length=1, verbose_name='Event type'),
        ),
    ]
