# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-26 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20151106_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmember',
            name='raw_image',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Member image file'),
        ),
        migrations.AddField(
            model_name='historicalmember',
            name='show_email',
            field=models.BooleanField(default=True, verbose_name='Allow members to see my email address'),
        ),
        migrations.AddField(
            model_name='historicalmember',
            name='show_phone',
            field=models.BooleanField(default=True, verbose_name='Allow members to see my phone number'),
        ),
        migrations.AddField(
            model_name='member',
            name='raw_image',
            field=models.ImageField(blank=True, null=True, upload_to='member_images', verbose_name='Member image file'),
        ),
        migrations.AddField(
            model_name='member',
            name='show_email',
            field=models.BooleanField(default=True, verbose_name='Allow members to see my email address'),
        ),
        migrations.AddField(
            model_name='member',
            name='show_phone',
            field=models.BooleanField(default=True, verbose_name='Allow members to see my phone number'),
        ),
        migrations.AlterField(
            model_name='historicalmember',
            name='address1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='historicalmember',
            name='address2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Address line 2'),
        ),
        migrations.AlterField(
            model_name='historicalmember',
            name='city',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='historicalmember',
            name='ghin',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='GHIN'),
        ),
        migrations.AlterField(
            model_name='historicalmember',
            name='handicap',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Handicap index'),
        ),
        migrations.AlterField(
            model_name='historicalmember',
            name='handicap_revision_date',
            field=models.DateField(blank=True, null=True, verbose_name='Handicap revision date'),
        ),
        migrations.AlterField(
            model_name='historicalmember',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='historicalmember',
            name='state',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='historicalmember',
            name='zip',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Zip Code'),
        ),
        migrations.AlterField(
            model_name='member',
            name='address1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='member',
            name='address2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Address line 2'),
        ),
        migrations.AlterField(
            model_name='member',
            name='city',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='member',
            name='ghin',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='GHIN'),
        ),
        migrations.AlterField(
            model_name='member',
            name='handicap',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Handicap index'),
        ),
        migrations.AlterField(
            model_name='member',
            name='handicap_revision_date',
            field=models.DateField(blank=True, null=True, verbose_name='Handicap revision date'),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='member',
            name='state',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='member',
            name='zip',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Zip Code'),
        ),
    ]
