# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-04 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20160426_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmember',
            name='raw_image',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Profile picture'),
        ),
        migrations.AlterField(
            model_name='member',
            name='raw_image',
            field=models.ImageField(blank=True, null=True, upload_to='member_images', verbose_name='Profile picture'),
        ),
    ]
