# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-04 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20160504_0953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalmember',
            name='show_phone',
        ),
        migrations.RemoveField(
            model_name='member',
            name='show_phone',
        ),
        migrations.AddField(
            model_name='historicalmember',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Birth date'),
        ),
        migrations.AddField(
            model_name='historicalmember',
            name='summary',
            field=models.TextField(blank=True, null=True, verbose_name='Summary'),
        ),
        migrations.AddField(
            model_name='member',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Birth date'),
        ),
        migrations.AddField(
            model_name='member',
            name='summary',
            field=models.TextField(blank=True, null=True, verbose_name='Summary'),
        ),
    ]
