# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-04 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20160604_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmember',
            name='status',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='member',
            name='status',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Status'),
        ),
    ]
