# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-30 13:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20160630_0843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalmember',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='member',
            name='parent',
        ),
    ]
