# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-21 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_member_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmember',
            name='payment_method',
            field=models.CharField(choices=[('S', 'Stripe'), ('P', 'PayPal')], default='S', max_length=1, verbose_name='Preferred payment method'),
        ),
        migrations.AddField(
            model_name='historicalmember',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Stripe ID'),
        ),
        migrations.AddField(
            model_name='historicalmember',
            name='stripe_save_card',
            field=models.BooleanField(default=False, verbose_name='Save credit card?'),
        ),
        migrations.AddField(
            model_name='member',
            name='payment_method',
            field=models.CharField(choices=[('S', 'Stripe'), ('P', 'PayPal')], default='S', max_length=1, verbose_name='Preferred payment method'),
        ),
        migrations.AddField(
            model_name='member',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Stripe ID'),
        ),
        migrations.AddField(
            model_name='member',
            name='stripe_save_card',
            field=models.BooleanField(default=False, verbose_name='Save credit card?'),
        ),
    ]
