# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-23 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20161021_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmember',
            name='dues_paid',
            field=models.BooleanField(default=False, verbose_name='Season dues paid'),
        ),
        migrations.AddField(
            model_name='member',
            name='dues_paid',
            field=models.BooleanField(default=False, verbose_name='Season dues paid'),
        ),
    ]
