# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-10 23:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20161127_1232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalmember',
            name='dues_paid',
        ),
        migrations.RemoveField(
            model_name='member',
            name='dues_paid',
        ),
        migrations.AddField(
            model_name='historicalmember',
            name='forward_tees',
            field=models.BooleanField(default=False, verbose_name='Forward tee player'),
        ),
        migrations.AddField(
            model_name='member',
            name='forward_tees',
            field=models.BooleanField(default=False, verbose_name='Forward tee player'),
        ),
    ]
