# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-12 23:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_auto_20170110_1759'),
        ('core', '0013_auto_20170110_1723'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Current golf season')),
                ('accept_new_members', models.BooleanField(default=False, verbose_name='Accepting new member registration?')),
                ('match_play_event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_play', to='events.Event', verbose_name='Match play event')),
                ('reg_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration', to='events.Event', verbose_name='Registration event')),
            ],
        ),
    ]
