# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-12 23:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_seasonsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seasonsettings',
            name='match_play_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_play', to='events.Event', verbose_name='Match play event'),
        ),
    ]
