# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-22 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20170112_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasonsettings',
            name='website_version',
            field=models.CharField(blank=True, max_length=10, verbose_name='Website version'),
        ),
    ]
