# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-07 04:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_seasonsettings_website_version'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ('user__last_name', 'user__first_name')},
        ),
    ]
