# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-12-26 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20170206_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmember',
            name='save_last_card',
            field=models.BooleanField(default=False, verbose_name='Save Last Card Used'),
        ),
        migrations.AddField(
            model_name='member',
            name='save_last_card',
            field=models.BooleanField(default=False, verbose_name='Save Last Card Used'),
        ),
    ]
