# Generated by Django 2.1.4 on 2018-12-11 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20171226_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalclub',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalmember',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='seasonsettings',
            name='match_play_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='match_play', to='events.Event', verbose_name='Match play event'),
        ),
        migrations.AlterField(
            model_name='seasonsettings',
            name='reg_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='registration', to='events.Event', verbose_name='Registration event'),
        ),
    ]
