# Generated by Django 2.2.10 on 2020-03-14 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20200107_2023'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'base_manager_name': 'objects', 'ordering': ('user__last_name', 'user__first_name')},
        ),
    ]
