# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-16 23:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpolicy',
            name='policy_type',
            field=models.CharField(choices=[('P', 'Policy or Procedure'), ('R', 'Local Rule'), ('S', 'Scoring and Handicap')], default='P', max_length=1, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='policy_type',
            field=models.CharField(choices=[('P', 'Policy or Procedure'), ('R', 'Local Rule'), ('S', 'Scoring and Handicap')], default='P', max_length=1, verbose_name='Type'),
        ),
    ]
