# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-11 02:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0002_auto_20160616_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpolicy',
            name='policy_type',
            field=models.CharField(choices=[('P', 'Policy or Procedure'), ('R', 'Local Rule'), ('S', 'Scoring and Handicap'), ('N', 'New Member Information'), ('A', 'About Us'), ('F', 'Payment FAQs')], default='P', max_length=1, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='policy_type',
            field=models.CharField(choices=[('P', 'Policy or Procedure'), ('R', 'Local Rule'), ('S', 'Scoring and Handicap'), ('N', 'New Member Information'), ('A', 'About Us'), ('F', 'Payment FAQs')], default='P', max_length=1, verbose_name='Type'),
        ),
    ]
