# Generated by Django 2.1.4 on 2018-12-11 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0003_auto_20170110_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpolicy',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
