# Generated by Django 2.1.4 on 2018-12-15 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0004_historicalpolicy_history_change_reason'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='policy',
            options={'verbose_name_plural': 'Policies'},
        ),
    ]
