# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-18 20:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0005_auto_20160207_1215'),
        ('events', '0010_eventcoursesetup_historicaleventcoursesetup'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_auto_20160604_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalSignupSlot',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('starting_order', models.IntegerField(default=0)),
                ('slot', models.IntegerField()),
                ('status', models.CharField(choices=[('A', 'Available'), ('P', 'Pending'), ('R', 'Reserved'), ('U', 'Unavailable')], default='A', max_length=1)),
                ('expires', models.DateTimeField(null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('course_setup_hole_id', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='courses.CourseSetupHole')),
                ('event', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='events.Event')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.Member')),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'verbose_name': 'historical signup slot',
                'get_latest_by': 'history_date',
            },
        ),
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_event_fee_paid', models.BooleanField(default=False)),
                ('is_greens_fee_paid', models.BooleanField(default=False)),
                ('is_gross_skins_paid', models.BooleanField(default=False)),
                ('is_net_skins_paid', models.BooleanField(default=False)),
                ('signed_up_by', models.CharField(max_length=60)),
                ('payment_confirmation_code', models.CharField(blank=True, max_length=120, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Member')),
            ],
        ),
        migrations.CreateModel(
            name='SignupReservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_hole', models.IntegerField()),
                ('starting_order', models.IntegerField(default=0)),
                ('course_setup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.CourseSetup')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
            ],
        ),
        migrations.CreateModel(
            name='SignupSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_order', models.IntegerField(default=0)),
                ('slot', models.IntegerField()),
                ('status', models.CharField(choices=[('A', 'Available'), ('P', 'Pending'), ('R', 'Reserved'), ('U', 'Unavailable')], default='A', max_length=1)),
                ('expires', models.DateTimeField(null=True)),
                ('course_setup_hole_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.CourseSetupHole')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Member')),
                ('signup_reservation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='signup.SignupReservation')),
            ],
        ),
        migrations.AddField(
            model_name='signup',
            name='signup_reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signup.SignupReservation'),
        ),
        migrations.AddField(
            model_name='historicalsignupslot',
            name='signup_reservation',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='signup.SignupReservation'),
        ),
    ]
