# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-19 14:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20160207_1215'),
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signupslot',
            old_name='course_setup_hole_id',
            new_name='course_setup_hole',
        ),
        migrations.RemoveField(
            model_name='historicalsignupslot',
            name='course_setup_hole_id',
        ),
        migrations.AddField(
            model_name='historicalsignupslot',
            name='course_setup_hole',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='courses.CourseSetupHole'),
        ),
    ]
