# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-01 01:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0003_auto_20160622_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalregistrationgroup',
            name='payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Payment amount'),
        ),
        migrations.AlterField(
            model_name='historicalregistrationgroup',
            name='payment_confirmation_timestamp',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Payment confirmation timestamp'),
        ),
        migrations.AlterField(
            model_name='registrationgroup',
            name='payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Payment amount'),
        ),
        migrations.AlterField(
            model_name='registrationgroup',
            name='payment_confirmation_timestamp',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Payment confirmation timestamp'),
        ),
    ]
