# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-21 22:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0004_auto_20160630_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupslot',
            name='registration_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='signup.RegistrationGroup', verbose_name='Group'),
        ),
    ]
