# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-05 00:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0016_auto_20161030_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('R', 'Event Results'), ('S', 'Season Long Points'), ('S', 'Dam Cup'), ('M', 'Match Play'), ('F', 'Dinancial Statements')], default='R', max_length=1, verbose_name='Type')),
                ('title', models.CharField(max_length=120, verbose_name='Title')),
                ('file', models.FileField(upload_to='documents/%Y', verbose_name='File')),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.Event', verbose_name='Event')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalDocument',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('R', 'Event Results'), ('S', 'Season Long Points'), ('S', 'Dam Cup'), ('M', 'Match Play'), ('F', 'Dinancial Statements')], default='R', max_length=1, verbose_name='Type')),
                ('title', models.CharField(max_length=120, verbose_name='Title')),
                ('file', models.TextField(max_length=100, verbose_name='File')),
                ('last_update', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('event', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='events.Event')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical document',
                'get_latest_by': 'history_date',
                'ordering': ('-history_date', '-history_id'),
            },
        ),
    ]
