# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-22 02:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('R', 'Event Results'), ('T', 'Event Tee Times'), ('S', 'Season Long Points'), ('D', 'Dam Cup'), ('M', 'Match Play'), ('F', 'Financial Statements')], default='R', max_length=1, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='document',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='events.Event', verbose_name='Event'),
        ),
        migrations.AlterField(
            model_name='historicaldocument',
            name='document_type',
            field=models.CharField(choices=[('R', 'Event Results'), ('T', 'Event Tee Times'), ('S', 'Season Long Points'), ('D', 'Dam Cup'), ('M', 'Match Play'), ('F', 'Financial Statements')], default='R', max_length=1, verbose_name='Type'),
        ),
    ]
