# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-07 04:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_auto_20170114_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('R', 'Event Results'), ('T', 'Event Tee Times'), ('P', 'Season Long Points'), ('D', 'Dam Cup'), ('M', 'Match Play'), ('F', 'Financial Statements'), ('S', 'Sign Up'), ('O', 'Other')], default='R', max_length=1, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='historicaldocument',
            name='document_type',
            field=models.CharField(choices=[('R', 'Event Results'), ('T', 'Event Tee Times'), ('P', 'Season Long Points'), ('D', 'Dam Cup'), ('M', 'Match Play'), ('F', 'Financial Statements'), ('S', 'Sign Up'), ('O', 'Other')], default='R', max_length=1, verbose_name='Type'),
        ),
    ]
