# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-26 22:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import documents.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0005_auto_20170206_2226'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalSponsor',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=40, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('website', models.CharField(max_length=240, verbose_name='Website URL')),
                ('level', models.CharField(choices=[('G', 'Gold'), ('S', 'Silver'), ('B', 'Bronze'), ('O', 'Other')], max_length=1, verbose_name='Level')),
                ('ad_image', models.TextField(blank=True, max_length=100, null=True, verbose_name='Ad Image')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical sponsor',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('website', models.CharField(max_length=240, verbose_name='Website URL')),
                ('level', models.CharField(choices=[('G', 'Gold'), ('S', 'Silver'), ('B', 'Bronze'), ('O', 'Other')], max_length=1, verbose_name='Level')),
                ('ad_image', models.ImageField(blank=True, null=True, upload_to='sponsor_images', verbose_name='Ad Image')),
            ],
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to=documents.models.document_directory_path, verbose_name='File'),
        ),
    ]
