# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-09-11 23:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import documents.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_auto_20170213_0652'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0006_auto_20170326_1734'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPhoto',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('photo_type', models.CharField(choices=[('DCT', 'Dam Cup Team'), ('DCP', 'Dam Cup Photos'), ('CC', 'Club Champion'), ('SCC', 'Senior Club Champion'), ('MW', 'Major Winner'), ('EP', 'Event Photos'), ('O', 'Other')], default='EP', max_length=3, verbose_name='Type')),
                ('year', models.IntegerField(default=0, verbose_name='Golf Season')),
                ('title', models.CharField(max_length=120, verbose_name='Title')),
                ('file', models.TextField(max_length=100, verbose_name='Image')),
                ('last_update', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('event', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='events.Event')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical photo',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_type', models.CharField(choices=[('DCT', 'Dam Cup Team'), ('DCP', 'Dam Cup Photos'), ('CC', 'Club Champion'), ('SCC', 'Senior Club Champion'), ('MW', 'Major Winner'), ('EP', 'Event Photos'), ('O', 'Other')], default='EP', max_length=3, verbose_name='Type')),
                ('year', models.IntegerField(default=0, verbose_name='Golf Season')),
                ('title', models.CharField(max_length=120, verbose_name='Title')),
                ('file', models.ImageField(upload_to=documents.models.photo_directory_path, verbose_name='Image')),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='events.Event', verbose_name='Event')),
            ],
        ),
    ]
