# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-22 02:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0005_auto_20160207_1215'),
        ('events', '0016_auto_20161030_1631'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0011_auto_20161023_0847'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_id', models.CharField(max_length=255, unique=True)),
                ('source', models.CharField(max_length=100)),
                ('currency', models.CharField(default='usd', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('amount_refunded', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('description', models.TextField(blank=True)),
                ('paid', models.NullBooleanField()),
                ('refunded', models.NullBooleanField()),
                ('captured', models.NullBooleanField()),
                ('receipt_sent', models.BooleanField(default=False)),
                ('charge_created', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='unknown', max_length=20)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='events.Event')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='core.Member')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalRegistration',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_event_fee_paid', models.BooleanField(default=False, verbose_name='Event fee is paid')),
                ('is_greens_fee_paid', models.BooleanField(default=False, verbose_name='Greens fee is paid')),
                ('is_gross_skins_paid', models.BooleanField(default=False, verbose_name='Gross skins are paid')),
                ('is_net_skins_paid', models.BooleanField(default=False, verbose_name='Net skins are paid')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.Member')),
            ],
            options={
                'get_latest_by': 'history_date',
                'verbose_name': 'historical registration',
                'ordering': ('-history_date', '-history_id'),
            },
        ),
        migrations.CreateModel(
            name='HistoricalRegistrationGroup',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('starting_hole', models.IntegerField(blank=True, verbose_name='Starting hole')),
                ('starting_order', models.IntegerField(default=0, verbose_name='Starting order')),
                ('notes', models.TextField(blank=True, verbose_name='Registration notes')),
                ('payment_confirmation_code', models.CharField(blank=True, max_length=120, verbose_name='Payment confirmation code')),
                ('payment_confirmation_timestamp', models.DateTimeField(blank=True, null=True, verbose_name='Payment confirmation timestamp')),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Payment amount')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('course_setup', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='courses.CourseSetup')),
                ('event', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='events.Event')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('signed_up_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.Member')),
            ],
            options={
                'get_latest_by': 'history_date',
                'verbose_name': 'historical registration group',
                'ordering': ('-history_date', '-history_id'),
            },
        ),
        migrations.CreateModel(
            name='HistoricalSignupSlot',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('starting_order', models.IntegerField(default=0, verbose_name='Starting order')),
                ('slot', models.IntegerField(verbose_name='Slot number')),
                ('status', models.CharField(choices=[('A', 'Available'), ('P', 'Pending'), ('R', 'Reserved'), ('U', 'Unavailable')], default='A', max_length=1, verbose_name='Status')),
                ('expires', models.DateTimeField(blank=True, null=True, verbose_name='Expiration')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('course_setup_hole', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='courses.CourseSetupHole')),
                ('event', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='events.Event')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.Member')),
            ],
            options={
                'get_latest_by': 'history_date',
                'verbose_name': 'historical signup slot',
                'ordering': ('-history_date', '-history_id'),
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_event_fee_paid', models.BooleanField(default=False, verbose_name='Event fee is paid')),
                ('is_greens_fee_paid', models.BooleanField(default=False, verbose_name='Greens fee is paid')),
                ('is_gross_skins_paid', models.BooleanField(default=False, verbose_name='Gross skins are paid')),
                ('is_net_skins_paid', models.BooleanField(default=False, verbose_name='Net skins are paid')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Member', verbose_name='Member')),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_hole', models.IntegerField(blank=True, verbose_name='Starting hole')),
                ('starting_order', models.IntegerField(default=0, verbose_name='Starting order')),
                ('notes', models.TextField(blank=True, verbose_name='Registration notes')),
                ('payment_confirmation_code', models.CharField(blank=True, max_length=120, verbose_name='Payment confirmation code')),
                ('payment_confirmation_timestamp', models.DateTimeField(blank=True, null=True, verbose_name='Payment confirmation timestamp')),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Payment amount')),
                ('course_setup', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.CourseSetup', verbose_name='Course')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event', verbose_name='Event')),
                ('signed_up_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Member', verbose_name='Signed up by')),
            ],
        ),
        migrations.CreateModel(
            name='SignupSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_order', models.IntegerField(default=0, verbose_name='Starting order')),
                ('slot', models.IntegerField(verbose_name='Slot number')),
                ('status', models.CharField(choices=[('A', 'Available'), ('P', 'Pending'), ('R', 'Reserved'), ('U', 'Unavailable')], default='A', max_length=1, verbose_name='Status')),
                ('expires', models.DateTimeField(blank=True, null=True, verbose_name='Expiration')),
                ('course_setup_hole', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.CourseSetupHole', verbose_name='Hole')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event', verbose_name='Event')),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Member', verbose_name='Member')),
                ('registration_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='register.RegistrationGroup', verbose_name='Group')),
            ],
        ),
        migrations.AddField(
            model_name='registration',
            name='registration_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.RegistrationGroup', verbose_name='Group'),
        ),
        migrations.AddField(
            model_name='historicalsignupslot',
            name='registration_group',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='register.RegistrationGroup'),
        ),
        migrations.AddField(
            model_name='historicalregistration',
            name='registration_group',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='register.RegistrationGroup'),
        ),
    ]
