# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-29 02:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_auto_20161030_1631'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0012_auto_20161127_1232'),
        ('courses', '0005_auto_20160207_1215'),
        ('register', '0003_auto_20161121_2214'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalRegistrationSlot',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('starting_order', models.IntegerField(default=0, verbose_name='Starting order')),
                ('slot', models.IntegerField(verbose_name='Slot number')),
                ('status', models.CharField(choices=[('A', 'Available'), ('P', 'Pending'), ('R', 'Reserved'), ('U', 'Unavailable')], default='A', max_length=1, verbose_name='Status')),
                ('expires', models.DateTimeField(blank=True, null=True, verbose_name='Expiration')),
                ('is_event_fee_paid', models.BooleanField(default=False, verbose_name='Event fee is paid')),
                ('is_greens_fee_paid', models.BooleanField(default=False, verbose_name='Greens fee is paid')),
                ('is_gross_skins_paid', models.BooleanField(default=False, verbose_name='Gross skins are paid')),
                ('is_net_skins_paid', models.BooleanField(default=False, verbose_name='Net skins are paid')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('course_setup_hole', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='courses.CourseSetupHole')),
                ('event', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='events.Event')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.Member')),
                ('registration_group', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='register.RegistrationGroup')),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'verbose_name': 'historical registration slot',
                'get_latest_by': 'history_date',
            },
        ),
        migrations.CreateModel(
            name='RegistrationSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_order', models.IntegerField(default=0, verbose_name='Starting order')),
                ('slot', models.IntegerField(verbose_name='Slot number')),
                ('status', models.CharField(choices=[('A', 'Available'), ('P', 'Pending'), ('R', 'Reserved'), ('U', 'Unavailable')], default='A', max_length=1, verbose_name='Status')),
                ('expires', models.DateTimeField(blank=True, null=True, verbose_name='Expiration')),
                ('is_event_fee_paid', models.BooleanField(default=False, verbose_name='Event fee is paid')),
                ('is_greens_fee_paid', models.BooleanField(default=False, verbose_name='Greens fee is paid')),
                ('is_gross_skins_paid', models.BooleanField(default=False, verbose_name='Gross skins are paid')),
                ('is_net_skins_paid', models.BooleanField(default=False, verbose_name='Net skins are paid')),
                ('course_setup_hole', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.CourseSetupHole', verbose_name='Hole')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='events.Event', verbose_name='Event')),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Member', verbose_name='Member')),
                ('registration_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slots', to='register.RegistrationGroup', verbose_name='Group')),
            ],
        ),
        migrations.RemoveField(
            model_name='charge',
            name='event',
        ),
        migrations.RemoveField(
            model_name='charge',
            name='member',
        ),
        migrations.RemoveField(
            model_name='historicalregistration',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalregistration',
            name='member',
        ),
        migrations.RemoveField(
            model_name='historicalregistration',
            name='registration_group',
        ),
        migrations.RemoveField(
            model_name='historicalsignupslot',
            name='course_setup_hole',
        ),
        migrations.RemoveField(
            model_name='historicalsignupslot',
            name='event',
        ),
        migrations.RemoveField(
            model_name='historicalsignupslot',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalsignupslot',
            name='member',
        ),
        migrations.RemoveField(
            model_name='historicalsignupslot',
            name='registration_group',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='member',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='registration_group',
        ),
        migrations.RemoveField(
            model_name='signupslot',
            name='course_setup_hole',
        ),
        migrations.RemoveField(
            model_name='signupslot',
            name='event',
        ),
        migrations.RemoveField(
            model_name='signupslot',
            name='member',
        ),
        migrations.RemoveField(
            model_name='signupslot',
            name='registration_group',
        ),
        migrations.DeleteModel(
            name='Charge',
        ),
        migrations.DeleteModel(
            name='HistoricalRegistration',
        ),
        migrations.DeleteModel(
            name='HistoricalSignupSlot',
        ),
        migrations.DeleteModel(
            name='Registration',
        ),
        migrations.DeleteModel(
            name='SignupSlot',
        ),
    ]
