# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-31 21:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_auto_20161128_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalregistrationgroup',
            name='card_verification_token',
            field=models.CharField(blank=True, max_length=30, verbose_name='Card verification token'),
        ),
        migrations.AddField(
            model_name='historicalregistrationslot',
            name='is_cart_fee_paid',
            field=models.BooleanField(default=False, verbose_name='Cart fee'),
        ),
        migrations.AddField(
            model_name='registrationgroup',
            name='card_verification_token',
            field=models.CharField(blank=True, max_length=30, verbose_name='Card verification token'),
        ),
        migrations.AddField(
            model_name='registrationslot',
            name='is_cart_fee_paid',
            field=models.BooleanField(default=False, verbose_name='Cart fee'),
        ),
        migrations.AlterField(
            model_name='historicalregistrationgroup',
            name='payment_confirmation_code',
            field=models.CharField(blank=True, max_length=30, verbose_name='Payment confirmation code'),
        ),
        migrations.AlterField(
            model_name='historicalregistrationslot',
            name='is_event_fee_paid',
            field=models.BooleanField(default=False, verbose_name='Event fee'),
        ),
        migrations.AlterField(
            model_name='historicalregistrationslot',
            name='is_greens_fee_paid',
            field=models.BooleanField(default=False, verbose_name='Greens fee'),
        ),
        migrations.AlterField(
            model_name='historicalregistrationslot',
            name='is_gross_skins_paid',
            field=models.BooleanField(default=False, verbose_name='Gross skins'),
        ),
        migrations.AlterField(
            model_name='historicalregistrationslot',
            name='is_net_skins_paid',
            field=models.BooleanField(default=False, verbose_name='Net skins'),
        ),
        migrations.AlterField(
            model_name='registrationgroup',
            name='payment_confirmation_code',
            field=models.CharField(blank=True, max_length=30, verbose_name='Payment confirmation code'),
        ),
        migrations.AlterField(
            model_name='registrationslot',
            name='is_event_fee_paid',
            field=models.BooleanField(default=False, verbose_name='Event fee'),
        ),
        migrations.AlterField(
            model_name='registrationslot',
            name='is_greens_fee_paid',
            field=models.BooleanField(default=False, verbose_name='Greens fee'),
        ),
        migrations.AlterField(
            model_name='registrationslot',
            name='is_gross_skins_paid',
            field=models.BooleanField(default=False, verbose_name='Gross skins'),
        ),
        migrations.AlterField(
            model_name='registrationslot',
            name='is_net_skins_paid',
            field=models.BooleanField(default=False, verbose_name='Net skins'),
        ),
    ]
