# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-07 23:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_auto_20161231_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalregistrationslot',
            name='expires',
        ),
        migrations.RemoveField(
            model_name='registrationslot',
            name='expires',
        ),
        migrations.AddField(
            model_name='historicalregistrationgroup',
            name='expires',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expiration'),
        ),
        migrations.AddField(
            model_name='registrationgroup',
            name='expires',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expiration'),
        ),
    ]
