# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-11 02:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_auto_20170107_1727'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='registrationslot',
            unique_together=set([('event', 'member')]),
        ),
    ]
