# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-15 00:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0007_auto_20170110_2030'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='registrationslot',
            unique_together=set([]),
        ),
    ]
