# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-21 02:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20170206_2226'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('register', '0009_auto_20170206_2226'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalRegistrationSlotPayment',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('card_verification_token', models.CharField(blank=True, max_length=30, verbose_name='Card verification token')),
                ('payment_code', models.CharField(blank=True, max_length=30, verbose_name='Payment code')),
                ('payment_timestamp', models.DateTimeField(blank=True, editable=False, verbose_name='Payment timestamp')),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Payment amount')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('recorded_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.Member')),
                ('registration_slot', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='register.RegistrationSlot')),
            ],
            options={
                'verbose_name': 'historical registration slot payment',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
        ),
        migrations.CreateModel(
            name='RegistrationSlotPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_verification_token', models.CharField(blank=True, max_length=30, verbose_name='Card verification token')),
                ('payment_code', models.CharField(blank=True, max_length=30, verbose_name='Payment code')),
                ('payment_timestamp', models.DateTimeField(auto_now=True, verbose_name='Payment timestamp')),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Payment amount')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Member', verbose_name='Member')),
                ('registration_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='register.RegistrationSlot', verbose_name='Registration')),
            ],
        ),
    ]
