# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-06-02 22:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0010_historicalregistrationslotpayment_registrationslotpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalregistrationslotpayment',
            name='comment',
            field=models.CharField(blank=True, max_length=200, verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='registrationslotpayment',
            name='comment',
            field=models.CharField(blank=True, max_length=200, verbose_name='Comment'),
        ),
    ]
