# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-09-11 23:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0011_auto_20170602_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationslot',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Member', verbose_name='Member'),
        ),
    ]
