# Generated by Django 2.1.4 on 2018-12-11 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0013_historicalregistrationrefund_onlinepayment_registrationrefund'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalregistrationgroup',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalregistrationrefund',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalregistrationslot',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalregistrationslotpayment',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registrationgroup',
            name='course_setup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='courses.CourseSetup', verbose_name='Course'),
        ),
        migrations.AlterField(
            model_name='registrationgroup',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='events.Event', verbose_name='Event'),
        ),
        migrations.AlterField(
            model_name='registrationgroup',
            name='signed_up_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Member', verbose_name='Signed up by'),
        ),
        migrations.AlterField(
            model_name='registrationrefund',
            name='recorded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Member', verbose_name='Recorded by'),
        ),
        migrations.AlterField(
            model_name='registrationslot',
            name='course_setup_hole',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='courses.CourseSetupHole', verbose_name='Hole'),
        ),
        migrations.AlterField(
            model_name='registrationslot',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='registrations', to='events.Event', verbose_name='Event'),
        ),
        migrations.AlterField(
            model_name='registrationslot',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Member', verbose_name='Member'),
        ),
        migrations.AlterField(
            model_name='registrationslotpayment',
            name='recorded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Member', verbose_name='Member'),
        ),
        migrations.AlterField(
            model_name='registrationslotpayment',
            name='registration_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='payments', to='register.RegistrationSlot', verbose_name='Registration'),
        ),
    ]
