# Generated by Django 2.1.4 on 2018-12-15 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0014_auto_20181210_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationgroup',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event', verbose_name='Event'),
        ),
        migrations.AlterField(
            model_name='registrationslot',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='events.Event', verbose_name='Event'),
        ),
    ]
