# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-07 18:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20151128_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesetuphole',
            name='course_setup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holes', to='courses.CourseSetup'),
        ),
        migrations.AlterField(
            model_name='hole',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holes', to='courses.Course'),
        ),
    ]
