# Generated by Django 2.1.4 on 2018-12-11 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20160207_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalcourse',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalcoursesetup',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalcoursesetuphole',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalhole',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='coursesetuphole',
            name='hole',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='courses.Hole'),
        ),
    ]
