# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-30 18:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0014_auto_20161023_0847'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_link_type', models.CharField(blank=True, choices=[('D', 'Detail Page'), ('T', 'Tee Time Page'), ('R', 'Results Page')], default='R', max_length=1, verbose_name='Link to')),
                ('external_url', models.CharField(blank=True, max_length=255, verbose_name='External url')),
                ('text', models.TextField(verbose_name='Announcement text')),
                ('starts', models.DateTimeField(verbose_name='Display start')),
                ('expires', models.DateTimeField(verbose_name='Display expiration')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.Event', verbose_name='Event')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalAnnouncement',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('event_link_type', models.CharField(blank=True, choices=[('D', 'Detail Page'), ('T', 'Tee Time Page'), ('R', 'Results Page')], default='R', max_length=1, verbose_name='Link to')),
                ('external_url', models.CharField(blank=True, max_length=255, verbose_name='External url')),
                ('text', models.TextField(verbose_name='Announcement text')),
                ('starts', models.DateTimeField(verbose_name='Display start')),
                ('expires', models.DateTimeField(verbose_name='Display expiration')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('event', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='events.Event')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'verbose_name': 'historical announcement',
                'get_latest_by': 'history_date',
            },
        ),
    ]
