# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-10 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='external_name',
            field=models.CharField(blank=True, max_length=40, verbose_name='External url name'),
        ),
        migrations.AddField(
            model_name='historicalannouncement',
            name='external_name',
            field=models.CharField(blank=True, max_length=40, verbose_name='External url name'),
        ),
    ]
