# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-10 16:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        ('messaging', '0002_auto_20161110_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='documents.Document', verbose_name='Document'),
        ),
        migrations.AddField(
            model_name='historicalannouncement',
            name='document',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='documents.Document'),
        ),
    ]
