# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-24 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_auto_20161110_1031'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Full name')),
                ('email', models.CharField(max_length=254, verbose_name='Email')),
                ('message_text', models.TextField(verbose_name='Message text')),
                ('message_date', models.DateTimeField(auto_now_add=True, verbose_name='Message date')),
            ],
        ),
    ]
