# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-09 23:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_contactmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='event_link_type',
        ),
        migrations.RemoveField(
            model_name='historicalannouncement',
            name='event_link_type',
        ),
        migrations.AddField(
            model_name='announcement',
            name='members_only',
            field=models.BooleanField(default=True, verbose_name='For members only?'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='title',
            field=models.CharField(blank=True, max_length=100, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='historicalannouncement',
            name='members_only',
            field=models.BooleanField(default=True, verbose_name='For members only?'),
        ),
        migrations.AddField(
            model_name='historicalannouncement',
            name='title',
            field=models.CharField(blank=True, max_length=100, verbose_name='Title'),
        ),
    ]
