# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-12-17 21:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0006_contact_historicalcontact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='president_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='President Phone'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='secretary_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Secretary Phone'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='treasurer_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Treasurer Phone'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='vice_president_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Vice-President Phone'),
        ),
        migrations.AlterField(
            model_name='historicalcontact',
            name='president_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='President Phone'),
        ),
        migrations.AlterField(
            model_name='historicalcontact',
            name='secretary_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Secretary Phone'),
        ),
        migrations.AlterField(
            model_name='historicalcontact',
            name='treasurer_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Treasurer Phone'),
        ),
        migrations.AlterField(
            model_name='historicalcontact',
            name='vice_president_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Vice-President Phone'),
        ),
    ]
