# Generated by Django 2.1.7 on 2019-04-07 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0008_auto_20181210_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalannouncement',
            name='document',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='documents.Document', verbose_name='Document'),
        ),
        migrations.AlterField(
            model_name='historicalannouncement',
            name='event',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='events.Event', verbose_name='Event'),
        ),
    ]
