# Generated by Django 2.2.10 on 2020-03-14 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0009_auto_20190407_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='non_members_only',
            field=models.BooleanField(default=False, verbose_name='For non-members only?'),
        ),
        migrations.AddField(
            model_name='historicalannouncement',
            name='non_members_only',
            field=models.BooleanField(default=False, verbose_name='For non-members only?'),
        ),
    ]
