# Generated by Django 2.2.10 on 2020-03-14 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0010_auto_20200314_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='members_only',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='non_members_only',
        ),
        migrations.RemoveField(
            model_name='historicalannouncement',
            name='members_only',
        ),
        migrations.RemoveField(
            model_name='historicalannouncement',
            name='non_members_only',
        ),
        migrations.AddField(
            model_name='announcement',
            name='visibility',
            field=models.CharField(choices=[('M', 'Members Only'), ('N', 'Non-members Only'), ('A', 'All')], default='A', max_length=1, verbose_name='Who should see the message?'),
        ),
        migrations.AddField(
            model_name='historicalannouncement',
            name='visibility',
            field=models.CharField(choices=[('M', 'Members Only'), ('N', 'Non-members Only'), ('A', 'All')], default='A', max_length=1, verbose_name='Who should see the message?'),
        ),
    ]
