# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-13 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolemember',
            name='is_officer',
            field=models.BooleanField(default=False, verbose_name='Is Officer'),
        ),
        migrations.AlterField(
            model_name='rolemember',
            name='is_chair',
            field=models.BooleanField(default=False, verbose_name='Is Chair'),
        ),
    ]
